apiVersion: v1
kind: Service
metadata:
  name: netology-svc
spec:
  selector:
    app.kubernetes.io/name: netology-web
  ports:
    - name: netology-svc
      protocol: TCP
      port: 8081
      targetPort: 8080
