apiVersion: v1
kind: Service
metadata:
  name: nginx-multitools-svc
spec:
  selector:
    app: nginx-multitools
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
    - protocol: TCP
      port: 8081
      targetPort: 8081
