apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-multitools
  template:
    metadata:
      labels:
        app: nginx-multitools
    spec:
      containers:
      - name: nginx
        image: nginx:latest
