apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app-name }}-backend-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app-name }}-backend
  ports:
    - name: backend
      protocol: TCP
      port: 9002
      targetPort: 8080
