apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appp-name  }}-backend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appp-name  }}-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appp-name  }}-backend
  template:
    metadata:
      labels:
        app: {{ .Values.appp-name  }}-backend
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:{{ .Values.multitool.image-tag }}
        env:
        - name: HTTP_PORT
          value: "8080"
        - name: HTTPS_PORT
          value: "8443"
