apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app_name }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.app_name }}-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: {{ .Values.app_name }}-frontend
  template:
    metadata:
      labels:
        app: {{ .Values.app_name }}-frontend
    spec:
      containers:
      - name: nginx
        image: nginx:{{ .Values.nginx_image_tag }}
