apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app_name }}-frontend-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.app_name }}-frontend
  ports:
    - name: {{ .Values.app_name }}-frontend
      protocol: TCP
      port: 9001
      targetPort: 80
