apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: nt.ksob.lan
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.app-name }}_frontend-svc
              port:
                number: 9001
        - path: /api
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.app-name }_backend-svc
              port:
                number: 9002
