apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool-nfs
  labels:
    app: multitool-nfs
spec:
 replicas: 1
 selector:
   matchLabels:
     app: multitool-nfs
 template:
   metadata:
     labels:
       app: multitool-nfs
   spec:
     containers:
     - name: multitool
       image: wbitt/network-multitool:latest
       volumeMounts: 
       - name: vol
         mountPath: /nfs
     volumes:
     - name: vol
       persistentVolumeClaim:
         claimName: multitool-nfs-pvc
---
    kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: multitool-nfs-pvc
    spec:
      storageClassName: "nfs"
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
