apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-logs-pvc
spec:
  storageClassName: local-storage
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100M 