apiVersion: v1
kind: Service
metadata:
  name: nginx-multitools-np-svc
spec:
  selector:
    app: nginx-multitools
  type: NodePort
  ports:
    - name: multitools
      protocol: TCP
      port: 9001
      targetPort: 8080
      nodePort: 30001
    - name: nginx
      protocol: TCP
      port: 9002
      targetPort: 80
      nodePort: 30002
