apiVersion: v1
kind: Service
metadata:
  name: nginx-multitools-svc
spec:
  selector:
    app: nginx-multitools
  ports:
    - name: multitools
      protocol: TCP
      port: 9001
      targetPort: 8080
    - name: nginx
      protocol: TCP
      port: 9002
      targetPort: 80
