apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: multibox-ds
  labels:
    app: multibox-ds
spec:
  selector:
    matchLabels:
      app: multibox-ds
  template:
    metadata:
      labels:
        app: multibox-ds
    spec:
      containers:
      - name: multitool
        image: wbitt/network-multitool:latest
        volumeMounts:
        - name: node-syslog
          mountPath: /node-syslog
      volumes:
      - name: node-syslog
        hostPath:
          path: /var/log/syslog
