apiVersion: apps/v1
kind: Deployment
metadata:
  name: multitool
  labels:
    app: multitool
spec:
 replicas: 1
 selector:
   matchLabels:
     app: multitool
 template:
   metadata:
     labels:
       app: multitool
   spec:
     containers:
     - name: busybox
       image: busybox
       command: ['sh','-c','while true; do date >> /data-logs/date-log.txt && sleep 5']
       volumeMounts:
       - name: tmp
         mountPath: /data-logs
     - name: multitool
       image: wbitt/network-multitool:latest
       command: ['sh','-c','while true; do cat /data-logs/date-log.txt']
       volumeMounts: 
       - name: tmp
         mountPath: /data-logs
     volumes:
     - name: tmp
       hostPath:
         path: /tmp/data-logs